# Render deployment configuration for Job Application Manager
# This file defines both the web service and PostgreSQL database

databases:
  - name: jobapp-db
    databaseName: jobapp_db
    user: jobapp_user
    plan: free

services:
  - type: web
    name: jobapp-api
    env: node
    plan: free
    nodeVersion: 18
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm run init:db && npm run migrate:db && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: jobapp-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
