export enum ApplicationStatus {
  APPLIED = 'Applied',
  WITHDRAW = 'Withdraw',
  IN_PROGRESS = 'In progress',
  REJECTED = 'Rejected',
  ACCEPTED = 'Accepted',
  JOB_OFFERED = 'Job Offered',
}

export enum EventType {
  PHONE_SCREEN = 'PHONE_SCREEN',
  TECHNICAL_INTERVIEW = 'TECHNICAL_INTERVIEW',
  BEHAVIORAL_INTERVIEW = 'BEHAVIORAL_INTERVIEW',
  CODING_CHALLENGE = 'CODING_CHALLENGE',
  TAKE_HOME_ASSIGNMENT = 'TAKE_HOME_ASSIGNMENT',
  ONSITE_INTERVIEW = 'ONSITE_INTERVIEW',
  REFERENCE_CHECK = 'REFERENCE_CHECK',
  NEGOTIATION = 'NEGOTIATION',
  OTHER = 'OTHER',
}
