name: Deploy to GitHub Pages

on:
  push:
    branches: [main, feature/analytics, fix/production-env-config]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Check versions
        run: |
          node --version
          npm --version
          pwd
          ls -la

      - name: Install dependencies
        run: |
          npm install --prefer-offline --no-audit
          npm cache clean --force

      - name: Build
        run: |
          npm run build
          ls -la dist/
        env:
          VITE_API_URL: https://jobapp-api-aryf.onrender.com/api
          VITE_API_BASE_URL: https://jobapp-api-aryf.onrender.com
          VITE_NODE_ENV: production
          VITE_APP_NAME: Job Application Manager

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/analytics' || github.ref == 'refs/heads/fix/production-env-config'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
